chore: try regex in conditional

diff --git a/.github/workflows/learn-github-actions.yml b/.github/workflows/learn-github-actions.yml
--- a/.github/workflows/learn-github-actions.yml
+++ b/.github/workflows/learn-github-actions.yml
@@ -31,17 +31,15 @@ jobs:
   validate-title:
     runs-on: ubuntu-latest
     steps:
-    - uses: 8BitJonny/gh-get-current-pr@1.4.0
-      id: PR
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        # Verbose setting SHA when using Pull_Request event trigger to fix #16
-        sha: ${{ github.event.pull_request.head.sha }}
-        # Only return if PR is still open
-        filterOutClosed: true
-    - run: |
-      if [[ ${prTitle} =~ a ]]; then
-        echo "::error file={name},line={line},endLine={endLine},title={title}::{message}" && exit 1
-      fi
-      env:
-        prTitle: ${{ steps.PR.outputs.pr_title }}
+      - uses: 8BitJonny/gh-get-current-pr@1.4.0
+        id: PR
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          # Verbose setting SHA when using Pull_Request event trigger to fix #16
+          sha: ${{ github.event.pull_request.head.sha }}
+          # Only return if PR is still open
+          filterOutClosed: true
+     - run: echo "::error file={name},line={line},endLine={endLine},title={title}::{message}" && exit 1
+        if: ${{ ab =~ a }}
+        env:
+          prTitle: ${{ steps.PR.outputs.pr_title }}
